services:
  mc:
    container_name: mc-server
    image: itzg/minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
        - "25565:25565"
    environment:
        EULA: "TRUE"
        VERSION: "1.20.1"
        ENABLE_AUTOPAUSE: "TRUE"
        OVERRIDE_SERVER_PROPERTIES: "FALSE"
        MAX_TICK_TIME: "-1"
        TYPE: "SPIGOT"
        MEMORY: "3G"
    volumes:
        # attach the relative directory 'data' to the container's /data path
        - /mc-data:/data
